spring:
  application:
    name: server
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB
  autoconfigure:
    exclude:
      - com.alibaba.cloud.ai.autoconfigure.dashscope.DashScopeAudioSpeechAutoConfiguration
      - com.alibaba.cloud.ai.autoconfigure.dashscope.DashScopeAudioTranscriptionAutoConfiguration
  profiles:
    active: dev
  datasource:
    url: jdbc:mysql://localhost:3306/blog?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    deepseek:
      chat:
        options:
          model: deepseek-v4-flash
    dashscope:
      embedding:
        enabled: true
        options:
          model: text-embedding-v4
    vectorstore:
      qdrant:
        host: localhost
        port: 6334
        collection-name: my-collection

knife4j:
  enable: true
  setting:
    language: zh_cn

r2:
  bucket: blog-test
  endpoint: https://b665f304b0fb94b0fc0977b20d94057d.r2.cloudflarestorage.com
  region: auto
  public-domain: http://xiyizi.top

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
